

class IntroModelClass {
  List<IntroDetails>? introDetails;

  IntroModelClass({this.introDetails});

  IntroModelClass.fromJson(Map<String, dynamic> json) {
    if (json['introDetails'] != null) {
      introDetails = <IntroDetails>[];
      json['introDetails'].forEach((v) {
        introDetails!.add(new IntroDetails.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.introDetails != null) {
      data['introDetails'] = this.introDetails!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class IntroDetails {
  int? id;
  String? screenName;
  String? language;
  String? labelType;
  var labelValue;
  int? screenOrder;
  bool? screenStatus;
  String? createdBy;
  String? createdDate;
  String? createdIp;
  var modifiedBy;
  var modifiedDate;
  var modifiedIp;
  String? displayName;

  IntroDetails(
      {this.id,
        this.screenName,
        this.language,
        this.labelType,
        this.labelValue,
        this.screenOrder,
        this.screenStatus,
        this.createdBy,
        this.createdDate,
        this.createdIp,
        this.modifiedBy,
        this.modifiedDate,
        this.modifiedIp,
        this.displayName});

  IntroDetails.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    screenName = json['screen_name'];
    language = json['language'];
    labelType = json['label_type'];
    labelValue = json['label_value'];
    screenOrder = json['screen_order'];
    screenStatus = json['screen_status'];
    createdBy = json['created_by'];
    createdDate = json['created_date'];
    createdIp = json['created_ip'];
    modifiedBy = json['modified_by'];
    modifiedDate = json['modified_date'];
    modifiedIp = json['modified_ip'];
    displayName = json['display_name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['screen_name'] = this.screenName;
    data['language'] = this.language;
    data['label_type'] = this.labelType;
    data['label_value'] = this.labelValue;
    data['screen_order'] = this.screenOrder;
    data['screen_status'] = this.screenStatus;
    data['created_by'] = this.createdBy;
    data['created_date'] = this.createdDate;
    data['created_ip'] = this.createdIp;
    data['modified_by'] = this.modifiedBy;
    data['modified_date'] = this.modifiedDate;
    data['modified_ip'] = this.modifiedIp;
    data['display_name'] = this.displayName;
    return data;
  }
}



class Autogenerated {
  int? id;
  String? screenName;
  String? language;
  String? labelType;
  Null? labelValue;
  int? screenOrder;
  bool? screenStatus;
  Null? createdBy;
  Null? createdDate;
  Null? createdIp;
  Null? modifiedBy;
  Null? modifiedDate;
  Null? modifiedIp;
  String? displayName;

  Autogenerated(
      {this.id,
        this.screenName,
        this.language,
        this.labelType,
        this.labelValue,
        this.screenOrder,
        this.screenStatus,
        this.createdBy,
        this.createdDate,
        this.createdIp,
        this.modifiedBy,
        this.modifiedDate,
        this.modifiedIp,
        this.displayName});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    screenName = json['screen_name'];
    language = json['language'];
    labelType = json['label_type'];
    labelValue = json['label_value'];
    screenOrder = json['screen_order'];
    screenStatus = json['screen_status'];
    createdBy = json['created_by'];
    createdDate = json['created_date'];
    createdIp = json['created_ip'];
    modifiedBy = json['modified_by'];
    modifiedDate = json['modified_date'];
    modifiedIp = json['modified_ip'];
    displayName = json['display_name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['screen_name'] = this.screenName;
    data['language'] = this.language;
    data['label_type'] = this.labelType;
    data['label_value'] = this.labelValue;
    data['screen_order'] = this.screenOrder;
    data['screen_status'] = this.screenStatus;
    data['created_by'] = this.createdBy;
    data['created_date'] = this.createdDate;
    data['created_ip'] = this.createdIp;
    data['modified_by'] = this.modifiedBy;
    data['modified_date'] = this.modifiedDate;
    data['modified_ip'] = this.modifiedIp;
    data['display_name'] = this.displayName;
    return data;
  }
}