class PaymentInvoiceModelClass
{

  var customeraccountid;
  var customermobilenumber;
  var customeraccountname;
  var numberofemployees;
  var baseamount;
  var netamountreceived;
  var servicechargerate;
  var servicechargeamount;
  var gstmode;
  var sgstrate;
  var sgstamount;
  var cgstrate;
  var cgstamount;
  var igstrate;
  var igstamount;
  var gstbaseamount;
  var customercontactname;
  var customeraddress;
  var acGstnumber;
  var statecode;
  var employername;
  var employeraddress;
  var employerstatename;
  var employercinno;
  var employerpanno;
  var employergstno;
  var amountinwords;
  var jurisdiction;
  var accountstatename;
  var pinumber;
  var pidate;

  PaymentInvoiceModelClass(
      {this.customeraccountid,
        this.customermobilenumber,
        this.customeraccountname,
        this.numberofemployees,
        this.baseamount,
        this.netamountreceived,
        this.servicechargerate,
        this.servicechargeamount,
        this.gstmode,
        this.sgstrate,
        this.sgstamount,
        this.cgstrate,
        this.cgstamount,
        this.igstrate,
        this.igstamount,
        this.gstbaseamount,
        this.customercontactname,
        this.customeraddress,
        this.acGstnumber,
        this.statecode,
        this.employername,
        this.employeraddress,
        this.employerstatename,
        this.employercinno,
        this.employerpanno,
        this.employergstno,
        this.amountinwords,
        this.jurisdiction,
        this.accountstatename,
        this.pinumber,
        this.pidate});

  PaymentInvoiceModelClass.fromJson(Map<String, dynamic> json) {
    customeraccountid = json['customeraccountid'];
    customermobilenumber = json['customermobilenumber'];
    customeraccountname = json['customeraccountname'];
    numberofemployees = json['numberofemployees'];
    baseamount = json['baseamount'];
    netamountreceived = json['netamountreceived'];
    servicechargerate = json['servicechargerate'];
    servicechargeamount = json['servicechargeamount'];
    gstmode = json['gstmode'];
    sgstrate = json['sgstrate'];
    sgstamount = json['sgstamount'];
    cgstrate = json['cgstrate'];
    cgstamount = json['cgstamount'];
    igstrate = json['igstrate'];
    igstamount = json['igstamount'];
    gstbaseamount = json['gstbaseamount'];
    customercontactname = json['customercontactname'];
    customeraddress = json['customeraddress'];
    acGstnumber = json['ac_gstnumber'];
    statecode = json['statecode'];
    employername = json['employername'];
    employeraddress = json['employeraddress'];
    employerstatename = json['employerstatename'];
    employercinno = json['employercinno'];
    employerpanno = json['employerpanno'];
    employergstno = json['employergstno'];
    amountinwords = json['amountinwords'];
    jurisdiction = json['jurisdiction'];
    accountstatename = json['accountstatename'];
    pinumber = json['pinumber'];
    pidate = json['pidate'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['customeraccountid'] = this.customeraccountid;
    data['customermobilenumber'] = this.customermobilenumber;
    data['customeraccountname'] = this.customeraccountname;
    data['numberofemployees'] = this.numberofemployees;
    data['baseamount'] = this.baseamount;
    data['netamountreceived'] = this.netamountreceived;
    data['servicechargerate'] = this.servicechargerate;
    data['servicechargeamount'] = this.servicechargeamount;
    data['gstmode'] = this.gstmode;
    data['sgstrate'] = this.sgstrate;
    data['sgstamount'] = this.sgstamount;
    data['cgstrate'] = this.cgstrate;
    data['cgstamount'] = this.cgstamount;
    data['igstrate'] = this.igstrate;
    data['igstamount'] = this.igstamount;
    data['gstbaseamount'] = this.gstbaseamount;
    data['customercontactname'] = this.customercontactname;
    data['customeraddress'] = this.customeraddress;
    data['ac_gstnumber'] = this.acGstnumber;
    data['statecode'] = this.statecode;
    data['employername'] = this.employername;
    data['employeraddress'] = this.employeraddress;
    data['employerstatename'] = this.employerstatename;
    data['employercinno'] = this.employercinno;
    data['employerpanno'] = this.employerpanno;
    data['employergstno'] = this.employergstno;
    data['amountinwords'] = this.amountinwords;
    data['jurisdiction'] = this.jurisdiction;
    data['accountstatename'] = this.accountstatename;
    data['pinumber'] = this.pinumber;
    data['pidate'] = this.pidate;
    return data;
  }
}
class Autogenerated {
  var customeraccountid;
  var customermobilenumber;
  var customeraccountname;
  var numberofemployees;
  var baseamount;
  var netamountreceived;
  var servicechargerate;
  var servicechargeamount;
  var gstmode;
  var sgstrate;
  var sgstamount;
  var cgstrate;
  var cgstamount;
  var igstrate;
  var igstamount;
  var gstbaseamount;
  var customercontactname;
  var customeraddress;
  var acGstnumber;
  var statecode;
  var employername;
  var employeraddress;
  var employerstatename;
  var employercinno;
  var employerpanno;
  var employergstno;
  var amountinwords;
  var jurisdiction;
  var accountstatename;
  var pinumber;
  var pidate;

  Autogenerated(
      {this.customeraccountid,
        this.customermobilenumber,
        this.customeraccountname,
        this.numberofemployees,
        this.baseamount,
        this.netamountreceived,
        this.servicechargerate,
        this.servicechargeamount,
        this.gstmode,
        this.sgstrate,
        this.sgstamount,
        this.cgstrate,
        this.cgstamount,
        this.igstrate,
        this.igstamount,
        this.gstbaseamount,
        this.customercontactname,
        this.customeraddress,
        this.acGstnumber,
        this.statecode,
        this.employername,
        this.employeraddress,
        this.employerstatename,
        this.employercinno,
        this.employerpanno,
        this.employergstno,
        this.amountinwords,
        this.jurisdiction,
        this.accountstatename,
        this.pinumber,
        this.pidate});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    customeraccountid = json['customeraccountid'];
    customermobilenumber = json['customermobilenumber'];
    customeraccountname = json['customeraccountname'];
    numberofemployees = json['numberofemployees'];
    baseamount = json['baseamount'];
    netamountreceived = json['netamountreceived'];
    servicechargerate = json['servicechargerate'];
    servicechargeamount = json['servicechargeamount'];
    gstmode = json['gstmode'];
    sgstrate = json['sgstrate'];
    sgstamount = json['sgstamount'];
    cgstrate = json['cgstrate'];
    cgstamount = json['cgstamount'];
    igstrate = json['igstrate'];
    igstamount = json['igstamount'];
    gstbaseamount = json['gstbaseamount'];
    customercontactname = json['customercontactname'];
    customeraddress = json['customeraddress'];
    acGstnumber = json['ac_gstnumber'];
    statecode = json['statecode'];
    employername = json['employername'];
    employeraddress = json['employeraddress'];
    employerstatename = json['employerstatename'];
    employercinno = json['employercinno'];
    employerpanno = json['employerpanno'];
    employergstno = json['employergstno'];
    amountinwords = json['amountinwords'];
    jurisdiction = json['jurisdiction'];
    accountstatename = json['accountstatename'];
    pinumber = json['pinumber'];
    pidate = json['pidate'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['customeraccountid'] = this.customeraccountid;
    data['customermobilenumber'] = this.customermobilenumber;
    data['customeraccountname'] = this.customeraccountname;
    data['numberofemployees'] = this.numberofemployees;
    data['baseamount'] = this.baseamount;
    data['netamountreceived'] = this.netamountreceived;
    data['servicechargerate'] = this.servicechargerate;
    data['servicechargeamount'] = this.servicechargeamount;
    data['gstmode'] = this.gstmode;
    data['sgstrate'] = this.sgstrate;
    data['sgstamount'] = this.sgstamount;
    data['cgstrate'] = this.cgstrate;
    data['cgstamount'] = this.cgstamount;
    data['igstrate'] = this.igstrate;
    data['igstamount'] = this.igstamount;
    data['gstbaseamount'] = this.gstbaseamount;
    data['customercontactname'] = this.customercontactname;
    data['customeraddress'] = this.customeraddress;
    data['ac_gstnumber'] = this.acGstnumber;
    data['statecode'] = this.statecode;
    data['employername'] = this.employername;
    data['employeraddress'] = this.employeraddress;
    data['employerstatename'] = this.employerstatename;
    data['employercinno'] = this.employercinno;
    data['employerpanno'] = this.employerpanno;
    data['employergstno'] = this.employergstno;
    data['amountinwords'] = this.amountinwords;
    data['jurisdiction'] = this.jurisdiction;
    data['accountstatename'] = this.accountstatename;
    data['pinumber'] = this.pinumber;
    data['pidate'] = this.pidate;
    return data;
  }
}

